// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/plexusone/agentcomms/ent/agent"
	"github.com/plexusone/agentcomms/ent/predicate"
)

// AgentUpdate is the builder for updating Agent entities.
type AgentUpdate struct {
	config
	hooks    []Hook
	mutation *AgentMutation
}

// Where appends a list predicates to the AgentUpdate builder.
func (_u *AgentUpdate) Where(ps ...predicate.Agent) *AgentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *AgentUpdate) SetTenantID(v string) *AgentUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableTenantID(v *string) *AgentUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *AgentUpdate) SetType(v agent.Type) *AgentUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableType(v *agent.Type) *AgentUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *AgentUpdate) SetConfig(v map[string]interface{}) *AgentUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *AgentUpdate) SetChannelID(v string) *AgentUpdate {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableChannelID(v *string) *AgentUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AgentUpdate) SetStatus(v agent.Status) *AgentUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableStatus(v *agent.Status) *AgentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// Mutation returns the AgentMutation object of the builder.
func (_u *AgentUpdate) Mutation() *AgentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := agent.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Agent.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := agent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Agent.status": %w`, err)}
		}
	}
	return nil
}

func (_u *AgentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(agent.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(agent.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(agent.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(agent.FieldChannelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(agent.FieldStatus, field.TypeEnum, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentUpdateOne is the builder for updating a single Agent entity.
type AgentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *AgentUpdateOne) SetTenantID(v string) *AgentUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableTenantID(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *AgentUpdateOne) SetType(v agent.Type) *AgentUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableType(v *agent.Type) *AgentUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *AgentUpdateOne) SetConfig(v map[string]interface{}) *AgentUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *AgentUpdateOne) SetChannelID(v string) *AgentUpdateOne {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableChannelID(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AgentUpdateOne) SetStatus(v agent.Status) *AgentUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableStatus(v *agent.Status) *AgentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// Mutation returns the AgentMutation object of the builder.
func (_u *AgentUpdateOne) Mutation() *AgentMutation {
	return _u.mutation
}

// Where appends a list predicates to the AgentUpdate builder.
func (_u *AgentUpdateOne) Where(ps ...predicate.Agent) *AgentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentUpdateOne) Select(field string, fields ...string) *AgentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Agent entity.
func (_u *AgentUpdateOne) Save(ctx context.Context) (*Agent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentUpdateOne) SaveX(ctx context.Context) *Agent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := agent.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Agent.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := agent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Agent.status": %w`, err)}
		}
	}
	return nil
}

func (_u *AgentUpdateOne) sqlSave(ctx context.Context) (_node *Agent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Agent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agent.FieldID)
		for _, f := range fields {
			if !agent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(agent.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(agent.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(agent.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(agent.FieldChannelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(agent.FieldStatus, field.TypeEnum, value)
	}
	_node = &Agent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
